// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 2.4.7.
// **********************************************************************

#ifndef __HEADPROTO_H_
#define __HEADPROTO_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;


namespace JFGameSoProto
{
    struct TSoMsg : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "JFGameSoProto.TSoMsg";
        }
        static string MD5()
        {
            return "bf1446a39cc9fa15d7005eec9f37e8e3";
        }
        TSoMsg()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            nVer = 0;
            nCmd = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(nVer, 0);
            _os.write(nCmd, 1);
            if (vecMsgData.size() > 0)
            {
                _os.write(vecMsgData, 2);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(nVer, 0, true);
            _is.read(nCmd, 1, true);
            _is.read(vecMsgData, 2, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["nVer"] = tars::JsonOutput::writeJson(nVer);
            p->value["nCmd"] = tars::JsonOutput::writeJson(nCmd);
            p->value["vecMsgData"] = tars::JsonOutput::writeJson(vecMsgData);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(nVer,pObj->value["nVer"], true);
            tars::JsonInput::readJson(nCmd,pObj->value["nCmd"], true);
            tars::JsonInput::readJson(vecMsgData,pObj->value["vecMsgData"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(nVer,"nVer");
            _ds.display(nCmd,"nCmd");
            _ds.display(vecMsgData,"vecMsgData");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(nVer, true);
            _ds.displaySimple(nCmd, true);
            _ds.displaySimple(vecMsgData, false);
            return _os;
        }
    public:
        tars::Short nVer;
        tars::Short nCmd;
        vector<tars::Char> vecMsgData;
    };
    inline bool operator==(const TSoMsg&l, const TSoMsg&r)
    {
        return l.nVer == r.nVer && l.nCmd == r.nCmd && l.vecMsgData == r.vecMsgData;
    }
    inline bool operator!=(const TSoMsg&l, const TSoMsg&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const TSoMsg&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,TSoMsg&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


}



#endif
